
[general]

	[general.relics]

		[general.relics.compatibility]
			warn_about_old_forge = true

		[general.relics.general]
			store_relic_owner = true
			#Range: 0.0 ~ 2.147483647E9
			damage_non_relic_owner_amount = 3.0
			leveling_bar_style = "||||||||||||||||||||||||||||||"
			leveling_bar_color_neutral = "#808080"
			leveling_bar_color_low = "#FF5555"
			leveling_bar_color_medium = "#FFFF55"
			leveling_bar_color_high = "#55FF55"

	[general.blocks]

		[general.blocks.pedestal]
			accept_any_item = true
			spawn_particles = true

